### PR TITLE
Fix `play list` not working

### PR DESCRIPTION
**Pull request by turbopope**
Adds a missing authorization header to the API request that searches for the playlist.
Also moves getting an auth token into a separate function.
Fixes #90.

### CODE REVIEW

**Comment by hnarayanan** [comment]
Thank you! Checking right now.

**Comment by hnarayanan** [comment]
It is superfluous, but could you please add trailing semicolons `;` after your two `getAccessToken` calls?

**Comment by turbopope** [comment]
Sure, done.

**Comment by hnarayanan** [comment]
Thank you!

**Pull request merged**
