### PR TITLE
Split out artist, track, and album display

### PR DESCRIPTION
**Pull request by rosscooperman**
I wanted to include artist, album, and track in my tmux status line so...

### CODE REVIEW

**Comment by rosscooperman** [comment]
I'm not opposed to nesting the commands under the status command.

**Comment by rosscooperman** [comment]
@hnarayanan updated the interface. thoughts?

**Comment by hnarayanan** [comment]
This looks good to me and thank you! I will take this for a spin when I next get the chance and merge it if I see no regressions to the status feature.

**Comment by rosscooperman** [comment]
Cool, thanks!

~Ross

On Sun, Jul 23, 2017 at 2:15 PM Harish Narayanan

<
mailto:Harish Narayanan <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

This looks good to me and thank you! I will take this for a spin when I next get the chance and merge it if I see no regressions to the status feature.

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/hnarayanan/shpotify/pull/78#issuecomment-317271573
, or

**Comment by hnarayanan** [comment]
Thank you!

**Comment by jsatk** [comment]
This rules. Thanks.

**Pull request merged**
