### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ericmarkmartin**
Added the `spotify vol show` command to the README

### CODE REVIEW

**Comment by tpritc** [comment]
While this technically right at the moment, I'm unsure if that's the desired way to invoke the 'Show Volume' command moving forward. We discussed this in #36, and it sounds like we're going to be removing `spotify vol show` soon, since `spotify vol` is the canonical way to show the volume.

**Comment by hnarayanan** [comment]
I tend to agree with Thomas. I am going to be away from my computer for some days, so will check on these pull requests after. But thank you for them. 😊

**Comment by tpritc** [comment]
If you wanted to change your PR to show this for `spotify vol`, that would be great. Looking at it now, if you could update [line 50 in the main script](https://github.com/hnarayanan/shpotify/blob/master/spotify#L50) to show `spotify vol` in the `spotify help` command, that'd be 😍.

Thanks for the PRs, I love seeing this project get updates!

**Comment by ericmarkmartin** [comment]
I'm going to close this PR because in #45 I added the README change and changed it from `vol show` to `vol`.

**Pull request closed without merging**
