### PR TITLE
one-letter aliases

### PR DESCRIPTION
**Pull request by pierreprinetti**
Because I'm lazy :)

### CODE REVIEW

**Comment by pierreprinetti** [comment]
I have slightly modified the behaviour of `play` to make it behave just like `pause` when used without further arguments. Therefore, `spotify p` (or `s p`, given `alias s=spotify` 😛 ) toggles play/pause.

**Comment by tpritc** [comment]
Some points from a quick glance (not at a personal machine so I can't pull the PR and test it):

- I like the indentation on the help. Looks great.
- I feel like `.editorconfig` should be in a different PR so we can discuss it separately from the one-letter change.
- As a stylistic point, I think we should use single quotes on the terminal, as is the case with `git help`:
```bash
'git help -a' and 'git help -g' list available subcommands and some
concept guides. See 'git help <command>' or 'git help <concept>'
to read about a specific subcommand or concept.
```
- Not sure about `st` for `status`. I'd argue for just `s`, to be consistent with the other shortcuts, but I understand that could cause a conflict of understanding with `share` and `toggle shuffle`.
- I love the idea of making this utility as easy to use as possible.

Thanks for the PR! Would love to hear @hnarayanan's opinion.

**Comment by hnarayanan** [comment]
I am still thinking about the rest :), but `.editorconfig` definitely has to be removed from the PR. This has nothing to do with this change.

**Comment by hnarayanan** [comment]
Also, thank you.

**Comment by pierreprinetti** [comment]
I have followed @tpritc's recommendations.
Speaking of `st`, I didn't want to collide with other related words as "**s**tart", "**s**top", or as you said, "**s**huffle" or "**s**hare". Furthermore, it's not uncommon to see `st` as an alias for `status` in GIT.

**Comment by ericmarkmartin** [comment]
In the README, could you update your `spotify vol` to indicate that `spotify vol` and `spotify vol show` do the same thing? I made changes to the docs to do that in #45 (which is probably why you have conflicts). If you could rebase and clean those up that would be nice.

**Comment by pierreprinetti** [comment]
zomg. rebased.

**Comment by pierreprinetti** [comment]
any news on this one? Please don't ask me to rebase again 😝

**Comment by hnarayanan** [comment]
No news. And you don't need to rebase. I or someone else will deal with this when we're ready. 😺 

The issue is the scope of the changes, and I am generally not ready to merge it without really carefully looking at it. And I never seem have the time.

**Comment by pierreprinetti** [comment]
bump :)

**Comment by hnarayanan** [comment]
Not forgotten, just busy! :)

**Comment by henrik242** [comment]
> I have slightly modified the behaviour of play to make it behave just like pause when used without further arguments. Therefore, spotify play (or s p, given alias s=spotify 😛 ) toggles play/pause.

Please don't.

**Comment by pierreprinetti** [comment]
please feel free to apply this diff in a different PR :)

**Pull request closed without merging**
