### PR TITLE
Feat/startup check

### PR DESCRIPTION
**Pull request by gbonetti**
Added check to run spotify if not running. I'm not super proud of the sleep statement but It's far the easiest way to get the right behaviour. 
Basically spotify doesn't accept any command until is fully loaded so it would't work without the sleep. A proper solution would be insert some check over the app state.
Also moved the fancy green-bold output creation to a function. Reset added to cleanup bash font settings after the output is completed.

### CODE REVIEW

**Comment by hnarayanan** [comment]
This is excellent, thank you. :+1: If you rename `fancyEcho` to `cecho` (for color echo), I will merge this pull request immediately.

**Comment by gbonetti** [comment]
I really loved FancyEcho :). But it's done.

**Comment by hnarayanan** [comment]
Excellent, thank you!

**Comment by hnarayanan** [comment]
And I forgot to mention, you might want to submit another pull request with your name as one of the contributors, both in the README and the script header. :)

**Comment by gbonetti** [comment]
No worries it's useful stuff, so I'm happy to contribute.

**Pull request merged**
