### PR TITLE
Adding search command

### PR DESCRIPTION
**Pull request by thepuzzlemaster**
Search for and start playing both a playlist or a track.

### CODE REVIEW

**Comment by thepuzzlemaster** [comment]
Oops. Forgot to update the README with the new commands. You mind doing that?

**Comment by hnarayanan** [comment]
You're free to submit another patch. :)

Also, I think I'm using the search feature wrong. What can I search for? I tried a track name and the gobbledegook part of the spotify URL (e.g. 7dIYMfQv5hyZ0I1S29MJIR).

**Comment by hnarayanan** [comment]
Super cool. It works with a plain text search of a song name as I now see. Just note that some search terms result in 502 errors on the server making the command fail.

**Comment by thepuzzlemaster** [comment]
Sure. I'll update them to specify what you should be searching for. In my testing, I didn't receive any 502 errors, but if it didn't find a song, it would not interrupt anything currently playing. What search terms have resulted in a 502?

**Comment by hnarayanan** [comment]
Also, think about this for a bit as I think this is amazing.

I think the interface should just be `./spotify play <foo>`, where `foo` is optional. If not specified, it does the old dumb play, but if specified, it does the new amazing thing of search and play.

**Comment by hnarayanan** [comment]
I think any search terms with spacebars (not sure), but here's one that doesn't work for me:

`curl -X GET "https://api.spotify.com/v1/search?q=the commander thinks aloud"`

**Comment by hnarayanan** [comment]
Also the curl output should be suppressed:

````
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   166  100   166    0     0   1502      0 --:--:-- --:--:-- --:--:--  1522

````

And apologies for so many messages, I am just excited by this feature and ideas/specs are coming to me in bits and pieces.

**Comment by hnarayanan** [comment]
Also, forget the 502 error business for now as I am not able to reproduce it anymore with the same search terms as before. It could've been a temporary glitch with their search API.

**Comment by thepuzzlemaster** [comment]
Ahhh right. I am actually using a separate process which ssh's to the machine to trigger spotify commands, so my search string is being interpreted as a single string. I've never coded in this language before, so this is a little new to me. 

I like the idea of extending play, although, one thing about that, is you won't be able to specify what you're searching for (track vs playlist, etc.) The API supports searching for any attribute (artist, album, track, playlist)

**Comment by hnarayanan** [comment]
Let me think about this for an evening then. I will try to specify a nice command line interface that makes this a bit more intuitive.

**Pull request merged**
