### PR TITLE
Play by uri

### PR DESCRIPTION
**Pull request by kievechua**
It's easier to get specific list by uri since Spotify support it in their app.

### CODE REVIEW

**Comment by hnarayanan** [comment]
Looks quite good. Can you give me an example URL to test this feature?

**Comment by kievechua** [comment]
Sure, you can try with this uri `spotify play uri spotify:user:spotify:playlist:1KuPMhQ4z7oIq3zdQEZP0V`
Or just get it from Spotify app "Copy Spotify URI"

**Comment by hnarayanan** [comment]
Very good. I would like to add one piece of functionality around this, so please help me design it.

I would like a command line interface to get this URI. So do you think it makes sense to add it as part of `spotify share` or `spotify status`? Having output somewhere intuitive like the following: `Spotify URI: spotify:user:spotify:playlist:1KuPMhQ4z7oIq3zdQEZP0V` could help people determine and keep a copy of this URI to be used with your feature in the future.

Please share your thoughts when you've had the time to think about it. Thank you!

**Comment by kievechua** [comment]
IMO, `spotify share` should only be implemented if you able to copy it to clipboard, else use `spotify status`.

**Comment by hnarayanan** [comment]
I think `spotify share` works well as a quick way to get a URL that you might want to share with a friend. So let us leave that as is.

`spotify status` could be expanded to show this URI. There is already a (hidden from the docs) a `spotify info` command that shows a whole bunch of things, not all interesting. Do you want to copy the URI portion of that output and add it to `spotify status`? Then I will merge this pull request and this is a cool feature. 😀

**Comment by hnarayanan** [comment]
Remember to update the instructions on the README and add yourself to the list of contributors as part of this pull request!

**Comment by alexfreska** [comment]
@hnarayanan I think it would be really useful to be able to play tracks by uri, as this is their universal identifier. What is the status of this PR?

**Comment by hnarayanan** [comment]
I haven't thought about it in a while, but the status of this PR is exactly as in the discussion above! It just needs a bit more work to be merged. 😄

**Comment by ericmarkmartin** [comment]
I think I can wrap this up, but I need someone's opinion on the modification to `spotify share`. As it stands, it shows the Spotify share url, and I can trivially add code to display the Spotify URI as well. However, `spotify share` also copies the Spotify share url to the clipboard. I can trivially change that to copy the URI, but I don't know which one you want.

One thought I had was to make `spotify share` into two sub-commands:

1. `spotify share url` which shows and copies the Spotify share url (the current behavior of `spotify share`
2. `spotify share uri` which shows and copies the Spotify URI.

Then you could either deprecate `spotify status` without the extra argument, default it to one of the two, or somehow combine the behaviors.

However, there very well may be better ways of approaching this.

**Comment by ericmarkmartin** [comment]
I realized that the changes that made this command work no longer seem to work (i.e. `spotify play uri [uri]` doesn't work). I can't update the code in this PR, so I made a new one (#48).

**Comment by hnarayanan** [comment]
Thank you, @kievechua. This functionality is now  Inc as part of a larger recent pull request.

**Pull request closed without merging**
