### PR TITLE
Added info switch for all details Spotify is offering

### PR DESCRIPTION
**Pull request by snipem**
This solution is inspired by https://github.com/dronir/SpotifyControl

### CODE REVIEW

**Comment by hnarayanan** [comment]
Let me think a bit about the UI here. I am not sure I want to see so much with the info command. It was intended more to be a simple status around the currently playing track.

However this much info is still useful so let me think about how else it can be used. Let me know if you have other ideas around this too.

**Comment by snipem** [comment]
You could rename my `info` switch to `dump` or leave it as it is, so that every available information is passed to the command line for later reuse using pipes and filters.

I would stick to the `status` switch for now and change it's output to something similar to the output of `mpc` (A command line client to MPD, http://www.musicpd.org/clients/mpc/):

**Comment by hnarayanan** [comment]
Let me think about this some more, but I am leaning toward what you've mentioned above:

1. Update `status` to look something like your screenshot above.
2. Add a new `status detailed` or something to show a lot more information.

**Comment by hnarayanan** [comment]
I'll merge this in as it is now, without exposing it in the docs (just yet). And then when we've figured out what a good user interface around this is, I'll then expose it.

Thank you!

**Pull request merged**
