### PR TITLE
Add Lyrics option

### PR DESCRIPTION
**Pull request by rogeliozarate**
An option to display lyrics using http://makeitpersonal.co
Assumes that there is curl installed in the system.

### CODE REVIEW

**Comment by hnarayanan** [comment]
This sounds like a great idea! Two things before I can merge this pull request.

1. When I try the functionality, as of right now I get the following warning instead of lyrics:

````
$ ./spotify lyrics
Can't locate URI/Escape.pm in @INC (@INC contains: /opt/local/lib/perl5/site_perl/5.16.3/darwin-thread-multi-2level /opt/local/lib/perl5/site_perl/5.16.3 /opt/local/lib/perl5/vendor_perl/5.16.3/darwin-thread-multi-2level /opt/local/lib/perl5/vendor_perl/5.16.3 /opt/local/lib/perl5/5.16.3/darwin-thread-multi-2level /opt/local/lib/perl5/5.16.3 .).
BEGIN failed--compilation aborted.
Can't locate URI/Escape.pm in @INC (@INC contains: /opt/local/lib/perl5/site_perl/5.16.3/darwin-thread-multi-2level /opt/local/lib/perl5/site_perl/5.16.3 /opt/local/lib/perl5/vendor_perl/5.16.3/darwin-thread-multi-2level /opt/local/lib/perl5/vendor_perl/5.16.3 /opt/local/lib/perl5/5.16.3/darwin-thread-multi-2level /opt/local/lib/perl5/5.16.3 .).
BEGIN failed--compilation aborted.
Artist: Kanye West
Album: Yeezus
Track: Black Skinhead
artist is empty
````

2. Is http://makeitpersonal.co the best source for lyrics? I haven't heard of them, but are you sure they're reasonably complete/popular and won't go out of business in a little while? :smile_cat:

**Comment by hnarayanan** [comment]
I think it's because you and I are using different default `perl`s.

**Comment by IeuanG** [comment]
Might I suggest that we use wget to stdout instead of curl? This would reduce the number of  dependencies that we need.

**Comment by hnarayanan** [comment]
@leuanG: 1. I am not sure macs come with wget. They do come with curl though.

2. I agree. It might be worth looking into something like http://genius.com

**Comment by IeuanG** [comment]
@hnarayanan: Heh, I always assumed it was the other way around. 
At first glance genius doesn't seem to give lyrics in api requests, just annotations and song metadata. I may have missed something however.

**Comment by rogeliozarate** [comment]
Hello,
1.- I choose makeitpersonal,co because it is about grabbing an url:
No response parsing required (json,xml,soap,html), no registration, no API key, no request payload nor token passing.
Other options are Lyric Wiki, Lyrics.com, Musixmatch, Genius.com but I haven't look in detail into them.
2.- I installed CURL and WGETl via Homebrew. I don't remember if they were default in OSX or different from GNU version.
Must be a default HTP client in the system to use in installation/updates.
I'll try to look in a fresh system.
3.- I use PERL because I assumed there were PERL legacy in almost all *nix systems.
When I discovered that the song and artist name must be escaped to call the URL, I googled for help and it came next to top and was the first working option in my systems.
I know, Works In My System is a really bad way to contribute. I am ashamed.
For the record, I am using:
- OS X 10.11.2 El Capitan
- curl 7.43.0 (x86_64-apple-darwin13.4.0) libcurl/7.43.0 SecureTransport zlib/1.2.5
- perl 5, version 18, subversion 2 (v5.18.2) built for darwin-thread-multi-2level

**Comment by hnarayanan** [comment]
Thank you for responding!

1. If you have the time, please do some research on these other sites since they seem bigger. I understand how easy-to-use your first choice is, and if you find out the others are too complicated, we can come back to it.

2. Macs come by default with curl, and shpotify already uses it so that is going to continue.

3. The perl problem is my biggest issue at the moment so please try to work around that without using anything special from homebrew.

**Comment by ericmarkmartin** [comment]
I presume it's now a moot point, but Macs in fact do not come with wget, which is why it is the first example on the [homebrew page](http://brew.sh/).

**Comment by BlueHatbRit** [comment]
Since we're using curl we should be able to do it this way:

`curl -s -G "http://makeitpersonal.co/lyrics" --data-urlencode "artist=$encoded_artist" --data-urlencode "title=$encoded_track"

With `--data-urlencode" we take the data provided and URL encode it. Normally this will go into the Body but with `-G` we force a GET request which appends them to the URL as shown in the man pages:

```
-G, --get
              When  used,  this  option will make all data specified with -d, --data, --data-binary or --data-urlencode to be
              used in an HTTP GET request instead of the POST request that otherwise would be used. The data will be appended
              to the URL with a '?' separator.
```

This would remove the dependency of perl, and as a bonus we reduce the number of lines of code :)

**Pull request closed without merging**
