### PR TITLE
Updating controls to match documentation

### PR DESCRIPTION
**Pull request by thepuzzlemaster**
- Changing search to 'play'
 - Adding myself to README

### CODE REVIEW

**Comment by thepuzzlemaster** [comment]
Feeling really good about this.

Learned a whole bunch.

All searches now follow your proposed documentation.
I updated the docs in the help() command to match the readme.
I updated the scripts to follow the same order as the readme

All 'searches' return the first result except for playlists, which returns 10 results and picks one randomly.

**Comment by tpritc** [comment]
Wow that looks brillo. I can't wait to play with this!

**Comment by hnarayanan** [comment]
Excellent. I've merged it and will poke around in the next days.

**Comment by hnarayanan** [comment]
And thank you very much.

**Comment by hnarayanan** [comment]
I think you're going to enjoy it @tpritc, it's really cool. Please point out any bugs or odd behaviours you see with the new command interface.

**Pull request merged**
