### PR TITLE
add use Spotify URl play

### PR DESCRIPTION
**Pull request by FuYaoDe**
I added use PlayList Link 、Album Link、Artist Link、Spotify URL  can be used . 
e.g. spotify play list https://open.spotify.com/user/spotifytaiwan/playlist/47baPUxFPZOL3WtwD5iFJz
Because I found some Chinese can't find , Use only URL

### CODE REVIEW

**Comment by hnarayanan** [comment]
Thanks for the patch. I am not sure what you're aiming to do. Could you please write a couple of sentences about what your code does so I can review it?

**Comment by FuYaoDe** [comment]
if command line is 
```
 spotify play list https://open.spotify.com/user/spotifytaiwan/playlist/47baPUxFPZOL3WtwD5iFJz
```
it wll play this list

if command line is 
```
 spotify play list spotify:user:spotifytaiwan:playlist:47baPUxFPZOL3WtwD5iFJz
```
it can also play

I want to use a settled URL put in crontab achieve a spotify alarm , at first I want to use search , but some Chinese playlist can't find , so I've got to scandalize.

**Comment by hnarayanan** [comment]
OK, thank you for the explanation. I will think about this and write back more later.

**Comment by hnarayanan** [comment]
Hello, is this the same functionality as this other pull request: https://github.com/hnarayanan/shpotify/pull/27 ?

If so, I am will merge that one instead because the changes to the source code are minimal, whereas your changes seems to do a lot.

**Comment by FuYaoDe** [comment]
That's right , That is what I want features

**Comment by hnarayanan** [comment]
I will clean up the other pull request and merge it. Thank you though for your earlier request though. :)

**Pull request closed without merging**
