### PR TITLE
Add homebrew installation instructions to readme

### PR DESCRIPTION
**Pull request by ubuntudroid**
shpotify is also available via homebrew. Installation is much easier that way than installing the script manually. Therefore I've added the homebrew instructions to the manual

### CODE REVIEW

**Comment by hnarayanan** [comment]
Thank you for this patch. This is a good idea, but I am a bit concerned that the version of the script on homebrew is a bit old. How do you say we proceed?

**Comment by ubuntudroid** [comment]
Well, the version seems to be current. Thought you were the maintainer. XD However maintaining the homebrew script should not be difficult at all and it eases installation by a large margin.

**Comment by hnarayanan** [comment]
Would you like to try taking over maintaining the homebrew package? I personally don't use homebrew so I am likely to forget keeping it up to date.

If you agree and show me how to check whether the package is up to date, I will merge your pull request. 😊

**Comment by ubuntudroid** [comment]
You can find the formula [here](https://github.com/Homebrew/homebrew-core/blob/10b85245dcef439b24dc76e8a9dac210d3027cdf/Formula/shpotify.rb). It includes a pointer to the latest 1.1.0 release.

I can have a look at that formula and make sure that it is updated as soon as you release an update - if others aren't faster that is. ;)

**Comment by tpritc** [comment]
Homebrew version doesn't seem to include #38, just FYI. Not sure whether that's a problem with the homebrew recipe or the `tar` here.

**Comment by hnarayanan** [comment]
Aha, my point made! If anyone is willing to take over ownership of the homebrew business (make sure the versions, packages or whatever stay up-to-date), I am happy to update the official docs to point to homebrew as the preferred way to install shpotify.

**Comment by tpritc** [comment]
Okay, so the problem seems to be that it's pointing to the `HEAD` at 1.0.0, when we want it to use the latest commit on `master`. Calling in @xu-cheng and @ilovezfs, the contributors to the formula.

Since the canonical version of shpotify is the `master` on this repo, should we just use the tar ball of the repo in whatever its latest state is? Would love to hear the thoughts of @ubuntudroid and the contributors to the formula.

**Comment by ilovezfs** [comment]
The problem is that the only way for us to allow a formula to point to the tip of master unconditionally is to "relegate" it to https://github.com/Homebrew/homebrew-head-only which significantly reduces its exposure to a wider audience and stigmatizes it. The fundamental assumption in homebrew is that stable spec == latest upstream tag, unless the tag is designated alpha/beta/rc/preview/whatever. Upstreams that don't use tags are considered to be "misbehaving" :)

**Comment by ilovezfs** [comment]
In extremely rare cases (I am aware of only two), a stable spec can be defined as a repository URL + a revision, without a tag name, and then a version name artificially assigned. Here are the two:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/x264.rb#L5-L6
https://github.com/Homebrew/homebrew-core/blob/master/Formula/colortail.rb#L4-L6

If you do attempt to get that method approved, one of the main questions will be how to assign version names in the absence of upstream tags specifying them.

**Comment by hnarayanan** [comment]
Just to jump in, I have no problem assigning tag names once in a while to define "releases." Is that all I need to do to ensure that the homebrew side of things automagically works? (Because @tpritc's comment above makes it seem like there is more work to do. And I am trying to parcel of the work to anyone else who really wants this because I personally do not use homebrew and will forget to check it.)

**Comment by tpritc** [comment]
Yeah the main problem is that we're specifying the `1.1.0` tar ball, but it's defaulting the `HEAD` to `1.0.0`. I don't have a lot of experience with Homebrew, but assuming it's cool that we stay with tagged releases (and I don't see why not), can we get it to default to the latest commit in that tar ball?

**Comment by ilovezfs** [comment]
Yep, if you create a tag that lets the stable spec be defined as a tarball + checksum (GitHub API automatically makes tarballs with stable checksums to be available for tags), or if the build requires the actual git repository in order to succeed (the tarballs don't have the .git directory nor do they contain any submodules), then the stable spec can be defined as the tag name + the git commit revision of the tag. The version name is then equal to the tag name (or at least derived from it in cases where it's not parsed perfectly automatically).

Note that we have a new command "brew bump-formula-pr," which lets you open a pull request to update the formula by running `brew bump-formula-pr --url="url of the tarball" --sha256="sha256 of the tarball" shpotify` or if the formula uses tag+revision instead of url+sha256, then `brew bump-formula-pr --tag="tag name" --revision="revision of the tag" shpotify`. So this can actually be scripted as parted of your tagging procedure if you feel like it.

**Comment by ilovezfs** [comment]
@tpritc 
>Yeah the main problem is that we're specifying the 1.1.0 tar ball, but it's defaulting the HEAD to 1.0.0. I don't have a lot of experience with Homebrew, but assuming it's cool that we stay with tagged releases (and I don't see why not), can we get it to default to the latest commit in that tar ball?

What do you mean by "defaulting the HEAD to 1.0.0"?

**Comment by ilovezfs** [comment]
>can we get it to default to the latest commit in that tar ball

No. The tarball's checksum would change ;)

**Comment by tpritc** [comment]
@ilovezfs
>What do you mean by "defaulting the HEAD to 1.0.0"?
Please excuse me if I'm misunderstanding how this all works, but I've installed shpotify using `brew install shpotify`. Now, when I use it, I see that it is only up to date to [this commit](https://github.com/hnarayanan/shpotify/commit/dfabdf274a7467036370245014b210a918017ff7), which is the one tagged `1.0.0`. What we want is to use the commit tagged `1.1.0`, which for some reason isn't happening, despite it specifying the `1.1.0` tarball.

Here's what I'm getting from `brew info`:
```bash
$ brew info shpotify
shpotify: stable 1.0.0, HEAD
Command-line interface for Spotify on a Mac
https://harishnarayanan.org/projects/shpotify/
/usr/local/Cellar/shpotify/1.0.0 (3 files, 13.9K) *
  Built from source on 2016-07-04 at 09:26:29
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/shpotify.rb
```

**Comment by ilovezfs** [comment]
What's the output of `brew cat shpotify` there?

**Comment by tpritc** [comment]
Looks like it's fine. I'm just an idiot for forgetting to `brew update && brew upgrade` before testing.

**Comment by hnarayanan** [comment]
So long story short, I need to do nothing except tag releases once in a while and the homebrew business will just work (without me needing to manually checksum anything or whatever)?

**Comment by tpritc** [comment]
@hnarayanan Looks like it. `1.1.0` looks good to me on Homebrew now.

:shipit:

**Comment by ilovezfs** [comment]
@hnarayanan As long as someone (doesn't have to be you) runs brew bump-formula-pr, or manually opens a pull request, so we can actually merge the updated formula to brew master, so that users will get it upon brew update + brew upgrade.

Note that the tarballs for a tag are like this: https://github.com/hnarayanan/shpotify/archive/1.1.0.tar.gz

And you can grab the checksum like this of course: openssl dgst -sha256 <(curl -s -L  https://github.com/hnarayanan/shpotify/archive/1.1.0.tar.gz)

The only gotcha is you have to `export HOMEBREW_DEVELOPER=1` otherwise the `brew bump-formula-pr` command is "hidden."

**Comment by hnarayanan** [comment]
Thank you.

@ubuntudroid, since you raised this, do you want to take responsibility for the above?

**Comment by tpritc** [comment]
Thanks, @ilovezfs. You've been super helpful!

**Comment by ilovezfs** [comment]
You're welcome :)
For what it's worth, I now I have the brew bump-formula-command sufficiently scripted so that I can do this:
```
bfpr shpotify
```
and it does the rest.

You could do the same.

**Comment by ubuntudroid** [comment]
@hnarayanan wow, just one day out of town and so much has happened here. 😮 👍 I can definitely take care of updating the homebrew formula as soon as a new release has gone live. I subscribed to the releases feed so should usually have the updates ready within a day or so.

**Comment by hnarayanan** [comment]
Ok, I merging this @ubuntudroid. The rest is up to you!

**Pull request merged**
