### PR TITLE
Add 'stop' command

### PR DESCRIPTION
**Pull request by marksim**
# Problem

Sometimes you want to be able to script spotify to stop, and don't want it to accidentially come on when it's paused already.
# Solution

Make a 'stop' command.

### CODE REVIEW

**Comment by hnarayanan** [comment]
This is a pretty good idea! Let me think a bit how it can be better merged with the existing pause command. (As I think they philosophically do the same thing).

**Comment by marksim** [comment]
Right,  pause just does the resume thing.  Maybe there is a "--no-resume"
option?

**Comment by marksim** [comment]
bump

**Comment by hnarayanan** [comment]
I think this is just a matter of making the existing `pause` command your new behaviour (which makes more sense that the existing behaviour)? i.e. Make `pause` stay paused if triggered when playback is paused.

This will remove the need for a separate `stop` command.

**Comment by hnarayanan** [comment]
I am sold. 😀 I am going to merge this instead of #86. Could someone please fix the typo in the documentation (unpausees) introduced by this PR?

**Comment by henrik242** [comment]
@hnarayanan Okay, here: #91

**Pull request merged**
